### ISSUE TITLE
Pysurvival

### ISSUE THREAD

**Issue by KaranMehta21** [shi-ang/SurvivalEVAL#2]
Hi Shi-ang, 

Thank you for creating this package. It's super useful however I couldn't find code for evaluating models from the pysurvival package for instance the deepsurv model. I'm keen to plot a calibration curve showing predicted risk versus observed risk for the deepsurv model I've trained. Please can you help?

Kind Regards,
Karan

**Comment by shi-ang** [comment]
Hi,

I've created a usage example for the PySurvival package. Please see this [link](https://github.com/shi-ang/SurvivalEVAL/blob/main/Examples/PySurvival_auton-survival_Example.ipynb).

Let me know if I've solved all your issues.
